version: '3'
services:

  server:
    build: .
    container_name: application
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - database
    restart: always
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
  database:
    environment:
      - POSTGRES_PASSWORD=00000
    ports:
      - "4000:5432"
    image: postgres
    container_name: iceCreamApi
    env_file:
      - .env